### ISSUE TITLE
Interop: encapsulate message-validation types and invariants into single source-of-truth library

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10882]
This should be extracted from the superchain-backend, once the backend is in a functional form, to make reuse of these core components easier across the stack.

This is part of the superchain backend, this could be the first step of the superchain backend. This is considered done when the library exists that implements the serialization and types per the spec.

**Comment by hamdiallam** [comment]
So I was viewing the `op-superchain` directory as the source of truth for message types and invariants. In order for it to be a source-of-truth library, are we thinking about a library outside of the monorepo?

Otherwise i'm not sure how op-geth would consume this library. The code duplication in op-geth would be minimal if necessary. We simply need the backend RPC interface and calldata decoding logic.

cc @tynes @protolambda

**Comment by tynes** [comment]
Ideally there is minimal logic in geth and as much as possible is in the sidecar service. Can it be built with no copy of the decoding logic?

**Comment by hamdiallam** [comment]
One approach that's plausible which you proposed is passing through the entire calldata to the over RPC so that op-geth doesn't need to be aware of any of the concrete message types & decoding logic. It'd only need to redefine the safety labels & calldata fn selector to look for.

A downside being an extra local rpc requests made for invalidations that could have been determined upfront in the mempool. This should be cheap though.

**Comment by protolambda** [comment]
Closing this, we have a types package, and should focus on the usage before creating an arbitrary package API
https://github.com/ethereum-optimism/optimism/tree/develop/op-supervisor/supervisor/backend/types
