### ISSUE TITLE
Interop: handle deposits with cross-L2 messages in derivation

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10887]
Deposits may not perform cross-L2 messages newer than the most recent sequencing-window, to ensure the synchronous validation of the deposit cross-L2 message can be verified within reasonable time and safely reproduced.

**Comment by tynes** [comment]
In practice does this look like making the sequencing window legible to the EVM so that we can revert in EVM?

Right now there is a standardness of the sequencing window but it isn't legible from within EVM. We would need to set it via the `SystemConfig` or hardcode it to be a certain value as part of the hardfork. If hardcoded, then we can hardcode the same value to be used in the require statement, preventing too new of cross chain messages when its a deposit tx.

I made a design doc about making it dynamic - https://github.com/ethereum-optimism/design-docs/pull/14

Its less work to hardcode it to a specific value but impacts things like L3s since the sequencing window is defined by base layer blocks and not time. If we made it dynamic, there there may be unknown side effects/edge cases

**Comment by ajsutton** [comment]
Not entirely sure I have all the details in my head, but we could also expose whether the current tx is a deposit transaction (which we need to for devnet 0 workaround to disable cross-L2 deposits) and then the `L2Inbox` contract could call the `SystemConfig` to get the current sequencer window.

**Comment by protolambda** [comment]
Closing this in favor of discussion in https://github.com/ethereum-optimism/optimism/issues/10867 which is closely related and describes the current proposed solution for deposit handling in the comments
