### ISSUE TITLE
Implement e2e test infrastructure for running the op-program

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#11653]
It should be feasible to easily run VMs on the op-program (with valid inputs) without instantiating the op-challenger and dispute games.

**Comment by ajsutton** [comment]
We can do this for `op-program` natively already: https://github.com/ethereum-optimism/optimism/blob/b7f818877805b8c89eb27f7480e1b7b817c9f467/op-e2e/system_fpp_test.go#L299

Would need an extra helper to execute cannon since it can't be directly called like op-program can but should be fairly straight forward.  Adding some helpers to abstract the test from the details of invoking op-program would make sense too, some of which is basically what the `testFaultProofProgramScenario` is trying to do.

**Comment by Inphi** [comment]
Closing as not needed. We have a fully working VM and the vm-runner also makes it easy to run the op-program on real workloads.
