### ISSUE TITLE
Add support for Hardhat logging from inside of smart contracts

### ISSUE THREAD

**Issue by CodeSandwich** [ethereum-optimism/optimism#1195]
**Is your feature request related to a problem? Please describe.**
When debugging a Solidity contract in Hardhat test environment, it's convenient to use `hardhat/console.sol`. Unfortunately when running tests on Optimism client, nothing is printed.

**Describe the solution you'd like**
I'd like to have `hardhat/console.sol` working like on Hardhat or an equivalent tool.

**Describe alternatives you've considered**
Add a different debugging tool, which would be just as useful?

**Additional context**
None.

**Comment by smartcontracts** [comment]
I see two options for doing this:
1. Capture these logs in the EVM inside Geth and print them out in the Geth logs. Users would have to do something along the lines of `docker-compose logs l2geth | grep "hardhat:".
2. Capture the logs and attach them to the receipt, then modify the `hardhat-ovm` plugin to print out the logs. That could be pretty cool but not sure how easy that is.

**Comment by smartcontracts** [comment]
I don't think we're going to be supporting this feature -- in the same way that Geth does not natively support this feature. In OVM 2.0, Optimistic Ethereum is extremely close to "just Geth". This means that your testing pattern should basically be the same -- test your contracts in Hardhat and then deploy to OE. I think we can close this since that testing pattern does allow you to use console.log.
