### ISSUE TITLE
MTCannon: Evaluate potential livelock scenarios

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11979]
## Description

Try to write a non-buggy Go-based test (see [example](https://github.com/ethereum-optimism/optimism/blob/418fb5e98061da931fdd5fa57436d7f4fc416500/cannon/mipsevm/multithreaded/instrumented_test.go#L37-L58)) that creates a livelock scenario where we have a couple of threads that are active (not waiting), but are not actually making progress.  This will allow us to experiment with mitigations.

**Comment by Inphi** [comment]
Let's timebox this to 2 days

**Comment by Inphi** [comment]
Triggering a livelock on Cannon can be done reliably using the Go `runtime` facility to configure when and where goroutines run on OS threads. Here's an example program:

```go
package main

import (
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"
	"syscall"
        "time"
)

func init() {
	// configure a large number of CPUs to ensure goroutines run on different Ms
	runtime.GOMAXPROCS(100)
	debug.SetMaxThreads(100)
	// Force each goroutine to stay on its OS thread
	runtime.LockOSThread()
}

func main() {
	var wg sync.WaitGroup
	var mu1, mu2 sync.Mutex
	var tid1, tid2 int

	t1 := func() {
		tid1 = tid()
		fmt.Printf("ThreadID (%d): t1 init\n", tid1)
		for {
			mu1.Lock()
			preempt()
			if !mu2.TryLock() {
				fmt.Printf("ThreadID (%d) TryLock failed\n", tid1)
				mu1.Unlock()
				continue
			}

			fmt.Printf("ThreadID (%d): t1 done\n", tid1)
			mu2.Unlock()
			mu1.Unlock()
			return
		}
	}

	t2 := func() {
		tid2 = tid()
		defer wg.Done()
		fmt.Printf("ThreadID (%d): t2 init\n", tid2)
		for {
			mu2.Lock()
			preempt()
			if !mu1.TryLock() {
				fmt.Printf("ThreadID (%d) TryLock failed\n", tid2)
				mu2.Unlock()
				continue
			}

			fmt.Printf("ThreadID (%d): t2 done\n", tid2)
			mu1.Unlock()
			mu2.Unlock()
			return
		}
	}

	wg.Add(2)
	go t1()
	go t2()
	wg.Wait()

	if tid1 == tid2 {
		panic("misconfigured program")
	}
}

func tid() int {
	return syscall.Gettid()
}

func preempt() {
    	time.Sleep(50 * time.Millisecond)
}
```

This example is the classic case where two threads access two mutexes out of order. On a typical Linux machine, one thread eventually acquires both mutexes, allowing execution to progress. However, in Cannon, this doesn't happen for the following reasons:
- A sleep (syscall) ensures that the other thread executes before the current thread is woken up. Once the other thread is scheduled, it acquires `mu2` and creates the livelock condition.
- The sleep syscall immediately causes preemption irrespective of the amount time requested. Cannon does not have a monotonic clock (although it's simulated for `clock_gettime`). Thus, it is possible that the sleeping thread is awoken almost immediately before its "sleep deadline". As a result, typical userspace mitigations that randomize the sleep time are ineffective.


## Mitigations

### Static Analysis

There are various ways to do this including Symbolic execution, which is very slow but simple to implement. More efficiently, CFG analysis methods see [J. Blieberger et al, "Static Detection of Livelocks in Ada Multitasking Programs" in Proceedings of the 12th Ada-Europe International Conference on Reliable Software Technologies
Geneva, Switzerland, 2007, pp. 69](https://d1wqtxts1xzle7.cloudfront.net/30761173/Nabil_Abdennahder_Reliable_Software_Technologie-libre.pdf?1392092742=&response-content-disposition=inline%3B+filename%3DHandling_temporal_faults_in_Ada_2005.pdf&Expires=1731858258&Signature=arhYEwvietnxicwehDbmni0WeiK5BQkQ15y2LUwWqthUANfJ93x65~wjjwSX9YLDvcdlJcxG6Hks6KaFnAlfTjVOsKtD00fvgyg7NKMLRYbw67eJgnwo8e3n3Z5I-n5W9YJZbO0TSJ3G5zAkOsm9ebLxI1NNQhWtK~ZSI-SQ8qvr6ScZXv9u3gBXasI~KboLeaXzVrdRCrWd8XBqaIa9dkXs4~EP~e4gAlVoBz4t2TemdSwYFq1TDLtTa8KmgTasT9~i6lErgq480qrpNazcc1uxbvTHUVy9~oI0myRynYv~7Md01o3XIs1HLWYZ5WmfeniJ3rBR3K1L0aSNWgRNdA__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA#page=81) which also applies to Go programs) can detect livelocks in average polynomial time with some false positives.

### Runtime

Runtime livelock detection methods typically increase the size of the fault proof. In many cases, the VM needs access to states $[i-j, i-j+1, ..., i-1]$ in order to detect a livelock for state $i$. Though the proof may be compressed at the expense of complicating the VM state by merkleizing the trace. More critically, this can increase the onchain execution of the STF for livelock checking unless simpler heuristics are used for the detection. Here are a few ways ways livelocks can be detected and mitigated:

- Elide preemption for sleeping threads. Force sleeping threads to be immediately runnable and schedule them. This effectively means preemption only occurs after `SCHED_QUANTUM` or futex wait.
- Proper monotonic clock for sleep syscall with slightly increased sleep times. I experimented with this approach for the above program and its effectiveness highly depends on how much additional time the VM causes threads to remain idle. The tradeoff is a much longer execution trace. 
- Pseudo-Randomized thread scheduling schedules the usual next thread at probability < 1. Avoids the out of order resource acquisition scenario, but isn't robust against all livelock patterns.
- Biased preemption. This requires the VM to maintain a livelock set of threads that are not progressing. This is easy to do using heuristics for thread progress (like stack traces and program counter). Once this livelock set is complete, the VM force schedules each of them until execution progresses.
- Optimistic dynamic `SCHED_QUANTUM`. You simply adjust quantum for RMW and futex operations. Very easy to implement and does not increase the size of the fault proof. But it's not very robust.


Mitigating livelocks via static analysis methods seems like the right approach to avoid complicating the proof and it should be looked into more in the future. The runtime approaches that tweak thread preemption has unclear tradeoffs for execution (illustrated by this comment showing the effect of changing `SCHED_QUANTUM`](https://github.com/ethereum-optimism/optimism/issues/11978#issuecomment-2383757893)). 
We can defer following up on this as it's unlikely that the current op-program has such issues. This is based on a cursory review of the Go runtime internals and a more detailed review of the op-program mutator for typical livelock patterns. To future-proof the guest program, we should revisit this.
