### ISSUE TITLE
contracts: Remove old `forge-std` related code

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#12212]
Now that we have updated `forge-std` as part of https://github.com/ethereum-optimism/optimism/pull/12149, we can make the following changes:
- We can delete https://github.com/ethereum-optimism/optimism/blob/6fce64773fe7f8d693477523bc9b1f41d7a921b0/packages/contracts-bedrock/test/libraries/SafeCall.t.sol#L16
- Replace `vm.keyExists` with `vm.keyExistsJson`
- Replace the `_readOr` functions in the `DeployConfig`

**Comment by smartcontracts** [comment]
@tynes can you provide more detail about what needs to be done for those second two bullet points? I think this would be a good first issue. OPL EVM Engineering can provide review.

**Comment by mds1** [comment]
- `vm.keyExists` is being deprecated in favor of the specific `keyExistsJson` and `keyExistsToml` variants
- [This PR](https://github.com/foundry-rs/forge-std/pull/605) updated the `StdJson` and `StdToml` libraries so you can `myJsonString.readOr("myKeyName", defaultValue)` instead of our own `_readOr` methods. (The issue description used to say `_envOr` but I fixed it to say _readOr)

Agreed this would be a good first issue
