### ISSUE TITLE
EVM Engineering: merge BridgeInitializer into CommonTest

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12674]
`Bridge_Initializer` extends `CommonTest` but only does a few small contract deployments. I feel like we can just merge this into `CommonTest` so that everything uses an identical testing pattern. Otherwise it's confusing when some contracts use `Bridge_Initializer` and others use `CommonTest`. 

Feedback welcome.

**Comment by smartcontracts** [comment]
cc @tynes

**Comment by tynes** [comment]
This is fine, it was originally done to try to reduce build time for some tests. The bigger thing that I would like to see is the setup of `FFI` being moved to its own contract that can be composed into `CommonTest` so that we can remove the need of using `CommonTest` for the stateless differential tests. Also [SystemConfigInit](https://github.com/ethereum-optimism/optimism/blob/06a7ce2301bbcc8663863468a01a2386222a0f0d/packages/contracts-bedrock/test/L1/SystemConfig.t.sol#L20) should be removed as well as [Events](https://github.com/ethereum-optimism/optimism/blob/06a7ce2301bbcc8663863468a01a2386222a0f0d/packages/contracts-bedrock/test/setup/Events.sol#L13) once we are on a more modern solc

**Comment by smartcontracts** [comment]
> Also [SystemConfigInit](https://github.com/ethereum-optimism/optimism/blob/06a7ce2301bbcc8663863468a01a2386222a0f0d/packages/contracts-bedrock/test/L1/SystemConfig.t.sol#L20) should be removed as well as [Events](https://github.com/ethereum-optimism/optimism/blob/06a7ce2301bbcc8663863468a01a2386222a0f0d/packages/contracts-bedrock/test/setup/Events.sol#L13) once we are on a more modern solc

For `Events`, which version of solc do we need to be able to remove it? Also, can `SystemConfigInit` be removed now? Or does that also need modern solc?
