### ISSUE TITLE
Warn/advise users about the amount of logs generated by /ops

### ISSUE THREAD

**Issue by voltrevo** [ethereum-optimism/optimism#1281]
**Is your feature request related to a problem? Please describe.**
Running /ops (`sudo docker-compose up`) generates enough logging to exhaust disk space (about 5GB/day in my case), leading to host issues.

**Describe the solution you'd like**
Warn users about this and point them to mitigations. In my case I configured `/etc/docker/daemon.json` like this:

```json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m",
    "max-file": "3"
  }
}
```

(After learning about disk exhaustion the hard way.)

**Describe alternatives you've considered**
It might be possible to configure something similar by default in `docker-compose.yml`.

**Additional context**
https://docs.docker.com/config/containers/logging/configure/

**Comment by tynes** [comment]
Thanks for pointing this out. The `docker-compose` setup isn't meant to be ran in production, it exists for local development and integration testing purposes. Open to having a PR opened that updates `ops/README` with this information

You should be able to increase the configured polling intervals which would decrease the amount of logs being generated.
- https://github.com/ethereum-optimism/optimism/blob/87459d5e4dcc843fc0758c4b1acf7bf957265ee8/ops/envs/dtl.env#L7
- https://github.com/ethereum-optimism/optimism/blob/87459d5e4dcc843fc0758c4b1acf7bf957265ee8/ops/envs/geth.env#L8

Also you should consider adding your user to the `docker` group so that you don't need to use `sudo` when running `docker` commands, see https://docs.docker.com/engine/install/linux-postinstall/
