### ISSUE TITLE
Syncing op-node from Erigon3 L1 node

### ISSUE THREAD

**Issue by tornadocontrib** [ethereum-optimism/optimism#13463]
Some L1 exec nodes like Erigon3 or Reth doesn't support the calls well, and it is not a requirement for Arbitrum nodes as well.

Would be great if we could skip calls while syncing the OP L2s

**Comment by tynes** [comment]
You could be able to use the following flag to turn it off:

https://github.com/ethereum-optimism/optimism/blob/d3a50acff5831aee28de941f3bd8bc9d06e6eff3/op-program/host/flags/flags.go#L103-L107

```
--l1.trustrpc true
```

**Comment by tornadocontrib** [comment]
@tynes Thanks would try now

**Comment by Giulio2002** [comment]
Hey - Erigon team here. I would like to chime in and say that this should be default behaviour or at least be very well documented. `eth_getProof` is not needed by most people running a VC chain because they will end up running their own node anyway. this is just a suggestion but I always need to direct people and troubleshoot optimism node issue for some reason when someone wants to sync with Erigon. another point is that  `eth_getProof` for historical query requires multiples  TBs in all clients.

**Comment by tornadocontrib** [comment]
Have synced op-geth with op-node on Erigon3 L1 using `--l1.rpckind="standard" --l1.trustrpc` though all good
