### ISSUE TITLE
replica-healthcheck exits when state root cannot be checked

### ISSUE THREAD

**Issue by yorickdowne** [ethereum-optimism/optimism#1994]
**Describe the bug**

There appears to be a race condition where replica-healthcheck tries to read state root when it's not available. This exits replica-healthcheck with a Go error `TypeError: Cannot read property 'stateRoot' of null`; and upon restart it can read the state root successfully.

**To Reproduce**

Run data-transport-later, l2geth and let them sync; run replica-healthcheck and observe it. This error happens with some regularity.

**System Specs:**
 - OS: Ubuntu 20.04, docker
 - Package Version (or commit hash): healthcheck 0.3.3, l2geth 0.5.5, data-transport-layer 0.5.10.

**Additional context**

```
replica-healthcheck_1   | {"level":30,"time":1641636187844,"msg":"Replica caught up with sequencer, waiting for next block"}
replica-healthcheck_1   | {"level":30,"time":1641636188848,"msg":"Replica caught up with sequencer, waiting for next block"}
replica-healthcheck_1   | TypeError: Cannot read property 'stateRoot' of null
replica-healthcheck_1   |     at HealthcheckServer.runSyncCheck (/opt/optimism/packages/replica-healthcheck/dist/healthcheck-server.js:130:72)
replica-healthcheck_1   |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
replica-healthcheck_1   |     at async /opt/optimism/packages/replica-healthcheck/dist/exec/run-healthcheck-server.js:28:5
replica-healthcheck_1   | {"level":30,"time":1641636191098,"msg":"Listening on port 3000"}
replica-healthcheck_1   | {"level":30,"time":1641636191254,"blockNumber":2090087,"msg":"State roots matching"}
replica-healthcheck_1   | {"level":30,"time":1641636191320,"sequencerHeight":2090090,"replicaHeight":2090087,"heightDifference":3,"msg":"Syncing from sequencer"}
replica-healthcheck_1   | {"level":30,"time":1641636191320,"msg":"Replica caught up with sequencer, waiting for next block"}
replica-healthcheck_1   | {"level":30,"time":1641636192467,"blockNumber":2090093,"msg":"State roots matching"}
```

**Comment by smartcontracts** [comment]
Ok I can confirm this is a legit bug and can be easily fixed. I'll describe the underlying issue and a proposed fix so that we can turn  this into a Good First Issue.

From the error you provided I was able to find the line of code where this bug was triggered:

https://github.com/ethereum-optimism/optimism/blob/94d8320cc9340b86bcbb2fead33d1e21ec6a0f76/packages/replica-healthcheck/src/healthcheck-server.ts#L196

It seems the bug occurs because `sequencerCorresponding` (the block being pulled from the Sequencer to check against) is returning `null`:

https://github.com/ethereum-optimism/optimism/blob/94d8320cc9340b86bcbb2fead33d1e21ec6a0f76/packages/replica-healthcheck/src/healthcheck-server.ts#L191-L194

Interestingly, `replicaLatest` is *not* null. This suggests that the replica is seeing a block that the Sequencer hasn't seen yet. It doesn't make sense for the replica to have a block that the Sequencer hasn't seen (since replicas follow the Sequencer). It's possible that there are some intermittent caching issues on the Sequencer endpoint being used for the healthcheck service. It might eventually be worth investigating exactly why the Sequencer block is coming back as `null` (I'll throw an issue for this in triage), but for now it seems more important to make sure that the healthcheck service doesn't crash when this happens.

Fix should be pretty easy, if the `sequencerCorresponding` block comes back as `null`, log something (`this.logger.warn`) and sleep for a few seconds before trying again (`await sleep(5000)`).

**Comment by yorickdowne** [comment]
I know why this happened. Oh boy. `DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT` and `REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER` pointed to two different URLs. That'd do it re "we have it but the health check provider doesn't know about it yet".

**Comment by smartcontracts** [comment]
@yorickdowne good to know! This seems like a common enough configuration that we should just handle this within the healthcheck server. I could imagine a number of reasons why the URLs would be different, e.g., wanting to keep production endpoints separated for the sake minimizing the impact of a failure on one endpoint.

**Comment by smartcontracts** [comment]
We fixed this as part of our new (updated) replica-healthcheck service.
