### ISSUE TITLE
When to use environment vs env files for Docker Compose files?

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2020]
Just a quick question. When are we supposed to use the `environment` section of a `docker-compose.yml` file and when should we use the `env_file` section? What's the rule of thumb here?

**Comment by gbalbuena** [comment]
As environment wiring tends to grow over time `.env` files are easier to maintain and include in compose yaml files

I'm my point of view, is better to decouple env values and use `env_file` instead of `environment` only/preferably when they are distributed across many compose defs.

Other benefits:
* DRY
* Force .env.<context> conventions
