### ISSUE TITLE
Invalid JSON-RPC response on Kovan testnet

### ISSUE THREAD

**Issue by palango** [ethereum-optimism/optimism#2049]
**Describe the bug**
I'm trying to deploy some contracts, but I'm running into invalid JSON-RPC responses of the official https://kovan.optimism.io endpoint.

I'm using brownie to deploy the contracts and added some logging. I ommited all uninteresting logs before, but can provide them if you need them. Below you see that the transaction to deploy the contract sends back a transaction hash. brownie then tries to get more informarion about this tx with the `eth_getTransactionByHash`, to which a result without either `result` or `error` keys is returned. According to the [specification](https://www.jsonrpc.org/specification) this is invalid and brownie crashes at this point.
```
{'jsonrpc': '2.0', 'result': HexBytes('0xab2d73293b8dba25fc4ee17dfad9b5d1f16c9c1bd43a4c8982291467141c650a'), 'id': 11}
Transaction sent: 0xab2d73293b8dba25fc4ee17dfad9b5d1f16c9c1bd43a4c8982291467141c650a
Making request. Method: eth_getTransactionByHash ('0xab2d73293b8dba25fc4ee17dfad9b5d1f16c9c1bd43a4c8982291467141c650a',)
{'jsonrpc': '2.0', 'id': 12}
  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy.py", line 13, in main
    MintableToken.deploy(int(1e18), {"from": deployer})
  File "brownie/network/contract.py", line 524, in __call__
    return tx["from"].deploy(
  File "brownie/network/account.py", line 510, in deploy
    receipt, exc = self._make_transaction(
  File "brownie/network/account.py", line 759, in _make_transaction
    receipt = TransactionReceipt(
  File "brownie/network/transaction.py", line 198, in __init__
    tx: Dict = web3.eth.get_transaction(HexBytes(self.txid))
  File "web3/eth.py", line 617, in get_transaction
    return self._get_transaction(transaction_hash)
  File "web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "web3/manager.py", line 188, in request_blocking
    return self.formatted_response(response,
  File "web3/manager.py", line 170, in formatted_response
    elif response['result'] in NULL_RESPONSES:
KeyError: 'result'
```

**To Reproduce**
1. Send a tx deploying a new contract
2. Call `eth_getTransactionByHash` with the returned tx hash

**Expected behavior**
The response should be valid and return information about the transaction.

**System Specs:**
 - OS: macOS
 - Package Version: Optimism Kovan testnet (Started not working on Friday, still happens as of now. Wasn't broken beginning of last week)

**Comment by smartcontracts** [comment]
Sounds like possibly another proxyd issue? cc @mslipper

**Comment by mslipper** [comment]
Yep, I'll have this fixed shortly.

**Comment by mslipper** [comment]
Hi @palango,

This should be fixed now. I deployed the contents of the above PR separately, since `develop` currently contains additional changes we want to test before deploying to Kovan. Please let me know if you see any other issues.

Note that last Friday we changed kovan.optimism.io to route most RPCs to infrastructure providers like Infura and Alchemy rather than the sequencer. We did this to match how mainnet works and protect the sequencer from experiencing too much load. This means that you'll need to retry for a couple of seconds if the transaction you just submitted comes back as `null` from the `eth_getTransactionByHash` endpoint. Most Ethereum libraries do this automatically, but I wanted to point this out in case brownie doesn't.

**Comment by palango** [comment]
@mslipper That fixed the problems for me, thanks for looking at it so quickly!
