### ISSUE TITLE
L1 Block Number bug for Block 15,000,000

### ISSUE THREAD

**Issue by cantjaso** [ethereum-optimism/optimism#3132]
There seems to be an issue with the L1 Block Number field that is present in the transaction for the Optimism block 15,000,000. The L1 Block Number that is returned by numerous node providers (Alchemy, Figment, QuickNode, etc.) for this block is 15,173,152. But according to https://optimistic.etherscan.io/tx/15000000, the L1 transaction that this Optimism block belongs to is located on Ethereum block 15,173,223.

**Comment by smartcontracts** [comment]
My guess is that you're looking at the batch in which that transaction was submitted to L1 to get the 15173223 number ([link here](https://optimistic.etherscan.io/batch/94908)). The L1 Block Number field doesn't come from the batch where the transaction was submitted to L1 but instead comes from the L1 block number corresponding to the last deposit immediately before the transaction was made. If you searched backwards from that block and stopped at the first deposit that you find, you would see that the L1 block in which that deposit was submitted is 15173152.

Going to close this since it isn't a bug.
