### ISSUE TITLE
batch-submitter-service docker container enters infinite error loop

### ISSUE THREAD

**Issue by alicantutumlu** [ethereum-optimism/optimism#3311]
When I try to make all steps in CONTRIBUTING.md, I am facing with an issue. Here is the steps I follow
git clone git@github.com:ethereum-optimism/optimism.git
```
cd optimism
yarn install
nvm use
yarn clean
yarn build
cd ops
export COMPOSE_DOCKER_CLI_BUILD=1 # these environment variables significantly speed up build time
export DOCKER_BUILDKIT=1
docker-compose build
```
When I complete the above steps, I don't get any error and it completes successfully.
Then, I run this command:
`docker-compose up`

I get this error loop from batch-submitter-service:
<img width="705" alt="Screen Shot 2022-08-25 at 11 04 10" src="https://user-images.githubusercontent.com/29749723/186613024-1bafa982-6332-4dfc-bb2f-2b5eaf300448.png">

Also, I just wonder how can I reach user interface. Which port should I use?

**Comment by ccamaleon5** [comment]
Hello, I got same errors.

**Comment by cyborgdennett** [comment]
This error happens when there is no tx to be made in L2. In the code, you can see where this occurs: 

https://github.com/ethereum-optimism/optimism/blob/74c63d3c626d9a81c55911f2998e519fedbdc093/batch-submitter/drivers/sequencer/encoding.go#L220-L228

I would suggest to add a new error check for this case in the bss-core service

https://github.com/ethereum-optimism/optimism/blob/74c63d3c626d9a81c55911f2998e519fedbdc093/bss-core/service.go#L184-L191

Something like:
```go
if err != nil {
    if err.Error() == "no new tx" {
        log.Debug(name+"no new tx detected")
        continue
    }
    log.Error(name+" unable to craft batch tx",
        err", err)
    continue
```
