### ISSUE TITLE
Please make sender match `tx.origin` in transactions traces when the transaction is sent from L1.

### ISSUE THREAD

**Issue by ytrezq** [ethereum-optimism/optimism#3849]
Currently, when sending a transaction from L1, sender is left unset in transaction trace on the L2 side, which makes as if transaction is sent from `address(0x0)` in block explorers.

Please change this in order to have the sender matching the `tx.origin` being used at the execution level.

**Comment by smartcontracts** [comment]
We need to figure out how to properly prioritize work on this. We would accept a PR to make this change, but we're focusing a majority of our effort on the upcoming Bedrock release and I'm not sure where this would fall in the priority list inside of OP Labs. Definitely inconvenient but will also be fixed by default in Bedrock.

**Comment by ytrezq** [comment]
@smartcontracts : and `bedrock` is scheduled for November the 11, right ?

**Comment by smartcontracts** [comment]
Bedrock doesn't currently have a scheduled release date yet

**Comment by ytrezq** [comment]
@smartcontracts : I have another unrelated question. There was an Ethereum hard fork called ᴇᴛʜᴘᴏᴡ which was made like Bitcoin Cash with Bitcoin. How I can withdraw my bridged ᴇᴛʜᴘᴏᴡ from the bridge contract like other peoples are doing ? (Every ᴇᴛʜ address that had Ethers received the same amount of ᴇᴛʜᴘᴏᴡ).
