### ISSUE TITLE
verifiedIndex in rollup_getInfo always 0

### ISSUE THREAD

**Issue by quickchase** [ethereum-optimism/optimism#3974]
According to documentation:
https://community.optimism.io/docs/developers/build/json-rpc/#rollup-getinfo

> rollup_getInfo
> Returns useful L2-specific information about the current node.
> verifiedIndex: QUANTITY - Index of the last tx that was ingested from a batch that was posted to L1

As far as I can tell the `verifiedIndex` value is ALWAYS `0`

Why? What purpose does this value serve? What is the significance of it always being 0? When is it not 0?

**Comment by quickchase** [comment]
Sorry, but can you explain it like I'm 5 lol

Under what circumstance is the value populated?

No RPC provider seems to populate this field.

**Comment by quickchase** [comment]
Also I take it by the Bedrock comment that this is a "Bedrock Fixes This" issue? 🙂

**Comment by smartcontracts** [comment]
Yeah this is definitely a "bedrock fixes this" issue but more in the sense that "bedrock makes this issue go away by removing that RPC endpoint entirely".

Basically there are two types of Optimism nodes right now, nodes that sync from L1 and nodes that sync from L2 (directly from the sequencer). Nodes that sync from L2 will always return zero. Nodes that sync from L1 will return an increasing value as the node syncs. 

You always get zero from infra providers because they're running nodes that sync directly from the sequencer. They need to do this because otherwise they would have to wait for blocks to be published to L1 which means they would be behind the sequencer by quite a bit.

In Bedrock we get rid of this distinction between L1 nodes and L2 nodes.

**Comment by quickchase** [comment]
Is there a way to determine which L2 block number has been "finalized" on the L1 chain without this value being populated?

In other words: If I call `eth_getBlockByNumber("finalized")` on Ethereum - I get back the finalized L1 block, and it's number. How do I then get the "finalized" L2 block (the last block number committed to L1 at that time)?

**Comment by smartcontracts** [comment]
I don't know if nodes that sync from L2 currently have this ability. After Bedrock you will be able to use "safe" and "finalized" to accomplish this.

**Comment by quickchase** [comment]
Thanks, Matthew Slipper told me I could query getTotalElements in the L1 contract. Seems to give me what I want. You can close this if you want.

**Comment by smartcontracts** [comment]
Ok! Great. Glad you were able to figure this out. Closing. Feel free to open additional issues if you have any further questions.
