### ISSUE TITLE
Depositing ETH from L1 to L2 costs too much gas

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#500]
An L1 -> L2 deposit looks as though it is costing ~240,000 gas which is significantly more than what you'd expect for a relatively simple transfer. The figure is large because the contracts do some rate limiting on the number of L1 -> L2 `enQueue`s. It seems like that could be optimized. As a first step, one should do an audit of this code path and try to profile what operations are inflating the gas cost.

**Comment by K-Ho** [comment]
cc @ben-chain @maurelian

**Comment by K-Ho** [comment]
Why do we need this mapping? https://github.com/ethereum-optimism/contracts/blob/d72f24e779b707b2799914e5723268638fe6cacd/contracts/optimistic-ethereum/OVM/bridge/messaging/Abs_BaseCrossDomainMessenger.sol#L60

**Comment by K-Ho** [comment]
We need to map out a few low hanging fruit here for decreasing deposit gas cost, as over 1,000 people will be depositing ETH in a couple weeks to use Synthetix Exchange

**Comment by K-Ho** [comment]
1. Remove the messageNonce (read the length of the CTC queue instead)
2. Remove the gas burn in `enqueue`
3. Remove the sentMessages mapping storage. (Later, add functionality for `replayMessage` that allows providing an inclusion proof to the queue element)
4. Generally clean up the gateway to make fewer cross contract calls

**Comment by maurelian** [comment]
K-Ho's changes are good suggestions, I'd have to look more closely to come up with more.

**Comment by K-Ho** [comment]
cc @elenadimitrova

**Comment by ben-chain** [comment]
WRT 4., I do not think the gateway does any more than the two minimum required calls for transferring and enqueueing.  1.-3. look great though and will be big improvements :D

**Comment by elenadimitrova** [comment]
Making constructor initialised variables `immutable` will also help with reducing storage reads

**Comment by tynes** [comment]
A deposit into zksync takes about 60,000 gas for reference, see:
https://etherscan.io/tx/0xe16b21b5c8eb3ee61e15663502c7bec3a982e5ca2187ff98f7fe72e094b80386

**Comment by elenadimitrova** [comment]
@tynes This tx is depositing ETH rather than ERC20 and is thus much lighter. Still we can improve our numbers for sure.

**Comment by tynes** [comment]
> @tynes This tx is depositing ETH rather than ERC20 and is thus much lighter. Still we can improve our numbers for sure.

Note that there is a way to deposit ETH directly, see https://github.com/ethereum-optimism/contracts/pull/311

**Comment by K-Ho** [comment]
do we want this in before regenesis?

**Comment by ben-chain** [comment]
In terms of headaches that might arise from this, the main thing should be if anywhere in the `message-relayer` service which completes withdrawals by providing the transaction and witness on L1 has some sort of assumption that messageNonces are strictly incrementing.  This is because using the `queue.length` as the nonce could mean someone else calls enqueue, so that the cross-domain message nonce being set by the `L1CrossDomainMessenger` would jump up by more than 1.  I don't *think* that the service makes this assumption -- should just use the value emitted by events -- but that would be the most likely thing I would expect to see breaking integration tests.

A general comment on the crossdomainmessengers is that IMO the `Abs_BaseCrossDomainMessenger` inheritance model is not particularly good, and especially with these changes, the implementations on L1 and L2 are even less symmetric.  So I think it could be worthwhile to break out a `Lib_CrossDomainUtils.sol` library for any shared pure functions we want to have, and then have the messengers still share an interface, but not inherit from a parent implementation.

**Comment by tynes** [comment]
> Remove the gas burn in `enqueue`

Have we considered making users pay a fee to the sequencer on L1 for the enqueue txs instead of burning the gas? The fee could attempt to cover the cost of the batch submission. The charged fee will always have to be a guess on how much the batch submission will cost without some sort of engineered hedging

**Comment by maurelian** [comment]
Re: @K-Ho's brief spec [above ](https://github.com/ethereum-optimism/optimism/issues/500#issuecomment-822843070)

> 3. Remove the `sentMessages` mapping storage. (Later, add functionality for `replayMessage` that allows providing an inclusion proof to the queue element)

A note about `replayMessage()`: it currently serves no purpose, but will be useful when we begin enforcing "[gas limit epochs](https://github.com/ethereum-optimism/optimism/blob/56c441a2e140efb8bebb29f00ad9bc3dfef2ce40/specs/protocol/components/execution.md#L135)", so it does make sense IMO to remove it for now, leaving some kind of note behind about it. 

When it is time to reimplement it, the way to do the inclusion proof will be to make a call to `CTC.verifyTransaction()`, verifying the transaction `enqueued` according to the call made in [`_sendXDomainMessage()`](https://github.com/ethereum-optimism/optimism/blob/56c441a2e140efb8bebb29f00ad9bc3dfef2ce40/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol#L342).

**Comment by ben-chain** [comment]
> > Remove the gas burn in `enqueue`
> 
> Have we considered making users pay a fee to the sequencer on L1 for the enqueue txs instead of burning the gas? The fee could attempt to cover the cost of the batch submission. The charged fee will always have to be a guess on how much the batch submission will cost without some sort of engineered hedging

I think this is a good idea although the devEx is worse because this would require paying ETH at the end of the deposit code path, which may be somewhat annoying to implement.  Curious of folks' thoughts on that.  I do think that the MVP gas reduction is just to not charge the extra gas any more, and delegate this work to a future ticket if we think the DoS is an actually pressing issue.

**Comment by TransmissionsDev** [comment]
The overhead for enqueue is already massive, I don't think it really makes sense to try to DOS via enqueue rn tbh.
