### ISSUE TITLE
messageStatus:2 - STATE_ROOT_NOT_PUBLISHE

### ISSUE THREAD

**Issue by wuzhanfly** [ethereum-optimism/optimism#5507]
Hello. I'm testing private chain with optimism stack. So I build optimism stack on top of private chain and both optimism and private l1 working separately, transactions and deployments etc all cool. I'm also experimenting with optimism sdk, anyway I have my crosschainmessenger with my the contract addresses from deployments and chain ids etc. Everything working fine deposit eth/erc20/send message fine. 
The problem is: withdrawal. 
Whenever I do withdrawal my "messageStatus:2 - STATE_ROOT_NOT_PUBLISHED". 
What might be the problem at this point?? 

Things I've checked: I put console output on optimism sdk crosschainmessenger(node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js) getMessageBedrockOutput() function and the error is L2OutputOracle: cannot get output for a block that has not been proposed'.
So, I've checked the L2OutputOracle contract and latestBlockNumber() is 0, FINALIZATION_PERIOD_SECONDS() is 12 if it makes any difference. 
Anyway, clearly something is wrong because L2OutputOracle.getL2OutputIndexAfter(uint256 _l2BlockNumber) requires _l2BlockNumber <= latestBlockNumber() .

So idk what to do to fix that yet, any help would be great thanks!
(In short: help me fixing my private stack withdraw, problem is always getting "messageStatus:2 - STATE_ROOT_NOT_PUBLISHED")

**Comment by smartcontracts** [comment]
You also need to run the `op-proposer`. We are working on getting this added to the docs. https://github.com/ethereum-optimism/optimism/pull/5391

**Comment by wuzhanfly** [comment]
#### After running op-proposer, the problem still exists

```bash
version:1.0.3
````

**Comment by smartcontracts** [comment]
Hmmm strange. What is your `finalizationPeriodSeconds` in your deploy config?

**Comment by nitantchhajed** [comment]
Same Issue with me too, It takes hours and my code gets stuck at **Line number 64**, after that line executes successfully, it gives error of alchemy RPC Connection Timed out. I have my OP-Proposer running since the start and my challenge period is 60 seconds. here is the link of L2 transaction 
https://testnet.racescan.io/tx/0x149286a4fbd31a03c1eefbdc6627159b32a38de928221d3bb752dcbfcc998111

My Contracts -
AddressManager: "0xBd3cbCe7Dbc6Bb7c33b36D4B5E2adf3F186701E4",   
            L1CrossDomainMessenger: "0x3B251e2998009AB5034228CB71E95D71D9869322",    
            L1StandardBridge: "0x40DB2D3424286bEc850Aeec030cA6cCf17D07636",   
            OptimismPortal: "0xfEEE0247901eCE2FD8a72371e0C8F4F5b081CacA",  
            L2OutputOracle: "0xe2A596B5cb0134b60FC0396c9cA82867F5b35073", 

![image](https://github.com/ethereum-optimism/optimism/assets/96972634/fb4400ab-2383-46f1-a3d9-1523cec51320)

**Comment by nitantchhajed** [comment]
@smartcontracts any solution for this withdraw issue ??

**Comment by antonio-altr** [comment]
Hi guys I have the same problem, and I'm not sure changing `l2OutputOracleSubmissionInterval` alone is enough.

What I notice:
1. `l2OutputOracleSubmissionInterval` is first used to wait for **L1 blocks** (below I've set it to 60 or ~12mins on Sepolia)
   ```
   t=2023-08-25T03:24:13+0000 lvl=info msg="L2 Output Submitter started"
   t=2023-08-25T03:24:30+0000 lvl=dbug msg="proposer submission interval has not elapsed" currentBlockNumber=0 nextBlockNumber=60
   t=2023-08-25T03:24:37+0000 lvl=dbug msg="proposer submission interval has not elapsed" currentBlockNumber=0 nextBlockNumber=60
   ...
   ```
2. Then, `l2OutputOracleSubmissionInterval` is also used for the number of **L2 blocks** to put in each state root txn published on L1
   ```
   Txn1   proposeL2Output _l2BlockNumber=60
   Txn1   proposeL2Output _l2BlockNumber=120
   Txn1   proposeL2Output _l2BlockNumber=180
   ...
   ```

This means if L2 is significantly faster (e.g., 2 seconds) than the L1 (e.g., Sepolia 12 seconds), then Proposer already falls behind right out the gate (due to step 1), and continues to lag even farther with each step 2 that passes.

For example, I have a testnet running for a week (using `l2OutputOracleSubmissionInterval=120`) and the Proposer has gradually fallen behind on publishing to the tune of 2.5 days' worth of L2 blocks.

Appreciate any help on this, thanks.
