### ISSUE TITLE
eth_syncing return data is not accurate

### ISSUE THREAD

**Issue by J1a-wei** [ethereum-optimism/optimism#5745]
**Describe the bug**
We ran the deploy test network and the blocks were synchronizing, but when I called  eth_syncing rpc interface returns a result of false. This means that this block has been synchronized with the latest, when I go to call ETH_ When blockNumber is reached, the height of the block continues to grow. eth_ The data returned by syncing is incorrect, which leads to a logical error in the external health check probe.

```
/ # curl localhost:8545 -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":false}
/ # curl localhost:8545 -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x7ba2e3"}
/ # curl localhost:8545 -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x7ba31a"}
```

**Expected behavior**

When the block height is not synchronized with the latest, call the  `eth_syncing` following result should be returned

result - The result is false if JSON Object is not syncing otherwise it's true:
- startingblock - The block at which the import started encoded as hexadecimal

- currentblock - The current block, same as eth_blockNumber encoded as hexadecimal

- highestblock - The estimated highest block encoded as hexadecimal

**Additional context**
op-geth:  us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:latest
op-node:  us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest

**Comment by tynes** [comment]
This is a known issue and the upcoming upgrade will fix this issue

**Comment by J1a-wei** [comment]
Updated bedrock and same issue.  Is there any other solution? @tynes

**Comment by protolambda** [comment]
The `eth_syncing` result corresponds to the geth long-range syncing, which Optimism currently does not utilize, since everything is processed block-by-block from L1 data. However, because the block-time is fixed, you can see if it's synced up by comparing the timestamp of the latest block with the expected timestamp on your system clock, with a margin of a few seconds.

Also try `optimism_syncStatus` on the op-node for detailed sync progress information.

And `net_peerCount` is expected to be 0 on op-geth. It syncs via p2p in the op-node instead, see p2p API here: https://github.com/ethereum-optimism/optimism/blob/develop/op-node/p2p/rpc_api.go (we're still working on docs for advanced functionality), specifically try `opp2p_peers true` on op-node to get a list of connected peers.

**Comment by J1a-wei** [comment]
@protolambda hi, Thanks for your answer, by the way, which value should I take to compare with the system time? When I call optimism_syncStatus rpc, I don't really understand the meaning of the return body.  result.current_l1.timestamp Use this time to compare with the system?
