### ISSUE TITLE
Incorrect using of eth_getBlockReceipts method

### ISSUE THREAD

**Issue by zekchan** [ethereum-optimism/optimism#5924]
**Describe the bug**
op-node uses blockHash instead of number with eth_getBlockReceipts request to erigon.

**To Reproduce**
1. Run op-node with OP_NODE_L1_RPC_KIND=erigon
1. Recieve error `rpc-error: 1:invalid argument 0: hex number > 64 bits from node`

**Expected behavior**
1. Sync goes normaly

**System Specs:**
 - OS: docker image
 - Package Version (or commit hash): 1.1.0

**Additional context**
https://github.com/ethereum-optimism/optimism/blob/00844c48df8861404ec32b2fa5ad1368e3d1082f/op-node/sources/receipts.go#L430 here op-node uses that method

**Comment by ajsutton** [comment]
hmm, that's going to be problematic - if `eth_getBlockReceipts` doesn't accept block hash then it can't be used. Requesting by number isn't safe with reorgs.

**Comment by protolambda** [comment]
Looks like erigon defined a separate method for fetching blocks by receipt, instead of being flexible with the argument type like other clients. See 
https://github.com/ledgerwatch/erigon/issues/6229
https://github.com/ledgerwatch/erigon/commit/287a3d1d6c90fc6a7a088b5ae320f93600d5a167
We can probably support that erigon method though

**Comment by protolambda** [comment]
Implemented support for the the erigon-specific version of this endpoint in #5935
