### ISSUE TITLE
op-node: unsafeL2Payloads blocks when receiving a block prior to unsafeL2Head

### ISSUE THREAD

**Issue by Kelvyne** [ethereum-optimism/optimism#6092]
**Describe the bug**
When activating the unsafeL2Payload queue, op-node stops processing the queue if a payload is older than the rollup's unsafeL2Head.

**To Reproduce**

It happens more frequently when the batches are pushed slower. 

**Expected behavior**

I'd expect the payload to be dropped and op-node would continue processing the queue

**System Specs:**
 - OS: Mac M1 inside Docker
 - Package Version (or commit hash): 62c7f3b05a70027b30054d4c8974f44000606fb7

**Additional context**

A way I found to fix this issue is to pop these payloads when processing the queue. I don't know if there is bad side-effects from this diff.

```dif
diff --git a/op-node/rollup/derive/engine_queue.go b/op-node/rollup/derive/engine_queue.go
index 6f6c2fa5e..0e5f67ac3 100644
--- a/op-node/rollup/derive/engine_queue.go
+++ b/op-node/rollup/derive/engine_queue.go
@@ -428,6 +428,11 @@ func (eq *EngineQueue) tryNextUnsafePayload(ctx context.Context) error {
 			eq.log.Info("skipping unsafe payload, since it does not build onto the existing unsafe chain", "safe", eq.safeHead.ID(), "unsafe", first.ID(), "payload", first.ID())
 			eq.unsafePayloads.Pop()
 		}
+
+    if uint64(first.BlockNumber) <= eq.unsafeHead.Number {
+      eq.log.Info("skipping unsafe payload, since it is older than unsafe head", "unsafe", eq.unsafeHead.ID(), "unsafe_payload", first.ID())
+      eq.unsafePayloads.Pop()
+    }
 		return io.EOF // time to go to next stage if we cannot process the first unsafe payload
 	}
```
I would love to submit a PR if this is the way to go.

**Comment by ajsutton** [comment]
@Kelvyne Apologies for the delay in responding to this. I agree this appears to be an issue - having p2p alt sync enabled can also trigger this I think because it's trying to backfill blocks and so there's multiple threads trying to fetch and queue blocks so could wind up re-adding a block to the queue that has already been imported.

And I think your fix makes sense as well. The unsafe head is strictly equal to or later than the safe head so we could just replace the safe head check with this unsafe check.
We'd also need to add a test for this case.

If you're still keen to submit a PR for this it would be appreciated and feel free to tag me to review.

**Comment by Kelvyne** [comment]
> @Kelvyne Apologies for the delay in responding to this. I agree this appears to be an issue - having p2p alt sync enabled can also trigger this I think because it's trying to backfill blocks and so there's multiple threads trying to fetch and queue blocks so could wind up re-adding a block to the queue that has already been imported.
> 
> And I think your fix makes sense as well. The unsafe head is strictly equal to or later than the safe head so we could just replace the safe head check with this unsafe check. We'd also need to add a test for this case.
> 
> If you're still keen to submit a PR for this it would be appreciated and feel free to tag me to review.

Thank you for the answer, i'll work on a PR asap :)
