### ISSUE TITLE
`evm_snapshot` for the OVM

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#617]
**Is your feature request related to a problem? Please describe.**
[Someone in our discord](https://discord.com/channels/667044843901681675/832331828072939530/835142058561241109) asked whether we have `evm_snapshot` implemented for the OVM.

Is this something that could be implemented in the near future?
What blockers prevent this feature from being added quickly?

**Comment by gakonst** [comment]
It cannot be implemented on `l2geth` because geth does not support this kind of snapshotting logic. It can be done if we used ethereumjs-vm and patched it for the OVM (we used to do that), but this is cumbersome to maintain and is not currently a priority. If anybody ends up building an OVM patch on top of the latest ethereumjs-vm, that'd be useful. Here's where we'd landed before: https://github.com/ethereum-optimism/ethereumjs-vm
