### ISSUE TITLE
Question regarding L2 event log history

### ISSUE THREAD

**Issue by TimDaub** [ethereum-optimism/optimism#6253]
gm,

I'm shipping a contract to L2 that is reliant on L2 event log history to be permanently available to my p2p network (Kiwi News: https://github.com/attestate/delegator2). On the FC contracts repo I found an interesting question being asked: https://github.com/farcasterxyz/contracts/issues/265 "Is L2 event history going to be permanently available?" (akin to L1 ETH mainnet event log history). Is the answer here: "Depends on the sequencer?"

**Comment by tynes** [comment]
The L2 event history is going to be permanently available given some caveats around the definition of "permanent". L1 has this concept of state expiry, where the nodes are expected to stop sending blocks older than a specific number over the p2p network and the nodes can start at a non 0 blocknumber. This technique can be used to remove the constantly increasing history in the database. This is to help make sure that the database doesn't grow too large, because it will push many users off of the network. Power users should be able to run without this mode on and keep all history around. The same sort of logic applies to L2s. With EIP 4844, the L2 p2p network will be responsible for sending blocks/logs around p2p since L1 nodes will expire the data, so it won't be recoverable from L1, but there will certainly eventually be software that indexes the 4844 blobs in a way that syncing L2 nodes can read. So you should be able to assume that the logs will be around permanently, altho the database sizes will be very large and sharded in 10+ years.

**Comment by protolambda** [comment]
Let us know if that answered your question. I'm going to close this issue as resolved. Please re-open if necessary. Cheers
