### ISSUE TITLE
op-service: http util cleanup

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6733]
- [ ] Remove unnecessary timer from ListenAndServeContext.
  I believe it would error synchronously anyway, so we can clean up the http server start.
- [ ] move op-node http package into op-service httputil (and update usages)

**Comment by AN-Drew207** [comment]
Hi! I would like to help in this issue, Can would I work on this? I'm looking for my first issue to work on it

**Comment by protolambda** [comment]
@AN-Drew207 sure! Open a PR and tag me in the PR description.

**Comment by Flocqst** [comment]
Hi, i also started working on this one yesterday, if this is already assigned no problem, forgot to mention that i was trying to contribute to this issue.

In any case, i made a PR although some verifications do not go through : 
- ci/circleci: contracts-bedrock-checks & ci/circleci: depcheck i cannot figure out why its failing yet
- op-e2e-HTTP-tests might be because of my removal of the timer from ListenAndServeContext ?

@AN-Drew207 feel free to look at what i've done.
@protolambda if you can give me any guidance on those failed checks i'd appreciate.

**Comment by trianglesphere** [comment]
If tests are failing, try making sure that your PR includes the latest changes from develop.
