### ISSUE TITLE
Take advantage of Docker's health checking functionality

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#677]
Something I noticed while debugging #570 and writing #676 is that Docker has a native `HEALTHCHECK` command and `docker-compose` has a native `healthcheck` configuration option. There is a nice sample repo [here](https://github.com/peter-evans/docker-compose-healthcheck) that demonstrates how we might be able to use it. [Here](https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/) is an opinionated article about how health checks should work too. We might benefit from this.

**Comment by tynes** [comment]
Thanks for the comment @reggieag - we currently do utilize a `wait-for-it.sh` like strategy but it seems to be unreliable due to what I believe is a bug in newer versions of Docker for Mac. See https://github.com/ethereum-optimism/optimism/blob/develop/ops/scripts/geth.sh and other files in `ops/scripts`

**Comment by smartcontracts** [comment]
Closing since this hasn't had any movement for several months and it seems unlikely that we'll do anything with it.
