### ISSUE TITLE
Devnet finalization error 

### ISSUE THREAD

**Issue by steph-rs** [ethereum-optimism/optimism#7019]
**Describe the bug**
During the operation of the local dev-net, blocks on l2 are not finalized.

**To Reproduce**
- Run bedrock-devnet
- Only the 0th block remains finalized

**Expected behavior**
The finalized block updates every 12 seconds (or so), as described in the config [here](https://github.com/ethereum-optimism/optimism/blob/96562692558e5c3851899488bcebe51fbe3b7f09/packages/contracts-bedrock/deploy-config/internal-devnet.json#L23).

**Screenshots**
![image](https://github.com/ethereum-optimism/optimism/assets/70902141/af0c679a-3917-4627-b947-cdcace54d280)

**System Specs:**
 - OS: Ubuntu 22.04
 - Package Version (or commit hash): develop/master/releasev1.13

**Additional context**
As seen in the screenshot, a lot of time has passed and many blocks have been created, but only the zeroth remains finalized.

**Comment by steph-rs** [comment]
Can you please attach the `A-bedrock-devnet` label to the issue?

**Comment by ajsutton** [comment]
The `finalized` block returned by op-geth is the latest L2 block that has data included in a finalized L1 block that the node has seen. Since the devnet L1 doesn't finalize blocks (it's not running a full PoS consensus) the finalized L2 block is also expected to remain at 0.

The `finalizationPeriodSeconds` setting you reference refers to the L2 output oracle contract and how fast proposed output roots are considered finalized which affects how long you have to wait before finalizing withdrawals. On mainnet that's 1 week, but its deliberately very short on the devnet to make testing withdrawals faster.
