### ISSUE TITLE
Creating L2 genesis alloc using pure javascript / typescript

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#7950]
Since I don't like dependencies I would like to know how hard would it be to dump genesis alloc for a new op-stack rollup based on a deploy-config JSON https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/deploy-config/getting-started.json.

Maybe I might be looking for implementing features of the go code here to js https://github.com/ethereum-optimism/optimism/tree/develop/op-chain-ops/genesis.

Since there are ethereumjs it wouldn't be technically impossible but I would like to know what is required to do so.

Thanks.

**Comment by tynes** [comment]
> Since I don't like dependencies

What about `node_modules`? That is where ethereumjs would live.

It should be possible to reimplement the [L2 genesis generation](https://github.com/ethereum-optimism/optimism/blob/96a24cc3f6f5bbbb8f42011988208619a41344fd/op-chain-ops/genesis/layer_two.go#L17) in typescript, read through the code to see what it does. Note that it will be getting new features over time so you will need to maintain it.

**Comment by kaliubuntu0206** [comment]
Yes, reading the code implementation would be

1. dump system contract storage slots using hardhat-storage-layout package

2. deploy contract on local hardhat network with required params, call every available storage slots

3. assemble them to new genesis.json

rollup.json would be easier since it only requires an address of a deployed contracts on L1 https://github.com/base-org/node/blob/main/mainnet/rollup.json
