### ISSUE TITLE
Simple price oracle implementation for system contracts

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#8007]
Would be great and productive for many op-stack chains if a sequencer could add basic price oracle to the L2 system contract and update it for every block.

Using Chainlink's VWAP prices would eliminate the inaccuracy for the price and it could be used for many dapps as a complementary price source along with their internal TWAP ones.

**Comment by ghost** [comment]
Here we go but it would be great to have some example oracles as a showcase and supported by default so that op-stack would be superior than other rollups

https://stack.optimism.io/docs/build/tutorials/add-attr/

**Comment by tynes** [comment]
That sounds like a great mod but that is not something that we can support by default because it breaks credible neutrality and there is no oracle system that cannot be manipulated. All oracle systems have too strong of trust assumptions to enshrine into the op stack at this time.

Follow up questions: What is the security model around chainlink's vwap? What prices does it report on?

**Comment by ghost** [comment]
@tynes I think it is a composite of various data sources https://github.com/smartcontractkit/external-adapters-js/tree/main/packages/sources. Explanation: https://docs.chain.link/data-feeds/price-feeds

Various money market protocols including Compound relies on the feed and I think having a default feed wouldn't be an endorsement to use it https://docs.compound.finance/v2/prices/

Yeah and I also believe it is a market for being manipulated not the oracle itself.

**Comment by tynes** [comment]
My previous points still stand. It would be a nice op stack mod but nothing we would consider as a core protocol feature
