### ISSUE TITLE
JS SDK: estimateL1Gas doesn't return correct value

### ISSUE THREAD

**Issue by elcryptoninja** [ethereum-optimism/optimism#8239]
**Describe the bug**
The method estimateL1Gas doesn't give the exact L1 gas used of the transaction 

**To Reproduce**

```
 const HASH = '0xd9fe2820aba65a22ee959f4c203ea34ffb3dedfeac39889783b77bf63a204a6f'

    const l2RpcProvider = optimismSDK.asL2Provider(
        new ethers.providers.JsonRpcProvider('<RPC_URL>')
    )
    let transaction = await l2RpcProvider.getTransaction(HASH)
    let receipt = await l2RpcProvider.getTransactionReceipt(HASH)
    let l1GasUsed = await optimismSDK.estimateL1Gas(l2RpcProvider, transaction)
    console.log('COMPUTED',l1GasUsed.toString())
    console.log('REAL', receipt.l1GasUsed.toString())
```

this output : 
```
COMPUTED 9108
REAL 9092
```

**Expected behavior**
optimismSDK.estimateL1Gas() should return the same as the receipt

Why is there a difference? I'm getting crazy over this

**Comment by ajsutton** [comment]
For the record, it would be better to post these kinds of questions in https://github.com/ethereum-optimism/developers/discussions

The difference is because the estimate is done based on the unsigned transaction whereas the actual cost is calculated based on the signed transaction.  L1 charges a different amount of gas for 0s in transaction data than it does for 1s (one of those crazy quirks of Ethereum...).  So the estimate uses a worst case where the signature is all `1` bits to compute the maximum possible L1 cost but in reality the signature will have some mix of 0s and 1s resulting in the actual cost always being slightly lower.

The estimate is done on the unsigned transaction primarily because it's a really bad idea to be signing transactions before you know what they might cost you.
