### ISSUE TITLE
Docker image dockerfile source

### ISSUE THREAD

**Issue by norswap** [ethereum-optimism/optimism#8277]
The devnet dockerfiles (e.g. [the execution engine](https://github.com/ethereum-optimism/optimism/blob/op-node/v1.3.0/ops-bedrock/Dockerfile.l2)) have been updated to use online images. I haven't been able to find the source for these easily, are they available somewhere?

I'm currently updating [roll-op](https://github.com/0xFableOrg/roll-op) to be compatible with v1.3.0, and visibility into these files helps me figure out if something needs to change.

**Comment by ajsutton** [comment]
These still come from the locally built images.  The docker image build process did get changed though in https://github.com/ethereum-optimism/optimism/pull/8242 so that there's a single `Dockerfile`. The build process for all the binaries reuses a heap of work so there's now a single build process that builds everything then it just copies the required executable into separate docker images for each component.  So the `Dockerfile` I think you're looking for is `ops/docker/op-stack-go/Dockerfile`.

The `docker-bake.hcl` in the top level is also a useful reference since that's the entry point to it all.  And you can use `make golang-docker` to build the images locally.

**Comment by norswap** [comment]
Fantastic, thanks for the info!
