### ISSUE TITLE
Enabled golang race detector in CI/Tests

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#8488]
The golang data race detector can find some bugs.
Usage Guide: https://go.dev/doc/articles/race_detector
Introduction blog: https://go.dev/blog/race-detector

**Comment by ajsutton** [comment]
Took a stab at running this to see what it showed up in https://github.com/ethereum-optimism/optimism/pull/8573

https://app.circleci.com/pipelines/github/ethereum-optimism/optimism?branch=aj%2Frace-detector has a run showing all the failures.  The e2e ws tests timed out so still not sure what it will take to get them passing.

Unit tests look viable to get fixed though I'm not sure how valuable they are given the vast majority of them are purely single threaded so data races wouldn't show up even if the code wasn't thread safe simply because there's only one thread in the unit test.

**Comment by BlocksOnAChain** [comment]
@sebastianst @ajsutton ok to close this one or is it still relevant?

**Comment by ajsutton** [comment]
Yeah I'd say close it. The results didn't seem particularly useful.

**Comment by BlocksOnAChain** [comment]
Closing this issue, no further steps needed.
