### ISSUE TITLE
gasUsed in `eth_getTransactionReceipt` should return the cumulative gasUsed

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#862]
**Is your feature request related to a problem? Please describe.**
Currently, when requesting a transaction receipt via `eth_getTransactionReceipt`, the `gasUsed` that we return displays the `gasUsed` from the point that the transaction exits the contract account until the end of execution. So if a transaction consumes 700k gas in the SequencerEntrypoint and the ECDSAContractAccount and runs over the 9m gas limit, then receipt.gasUsed will show 8.3m gas. 

This has been confusing, because it's unclear how much gas was *actually* consumed by execution. It also makes developers think that their transaction didn't actually run out of gas, when it did because gasUsed will display some number in the low 8m gas, implying that there is still room for more execution

**Describe the solution you'd like**
* `transactionReceipt.gasUsed` will be the *total* execution gas used including the entrypoint and the ECDSAContractAccount  gas consumed. If I check the gasUsed for this test https://github.com/ethereum-optimism/optimism/issues/761, I should see 9m gasUsed

**Additional context**
* We may have to think deeper about how this plays into the idea of a user sending a transaction with an execution gasLimit, and if that gasLimit applies only after the transaction leaves the user's contract account...
* This would have saved a few days of Scopelift's time debugging a failed contract deployment

**Comment by smartcontracts** [comment]
I do not believe this is an easy problem to solve. The fundamental issue at hand is described here: https://github.com/ethereum-optimism/optimism/issues/874#issuecomment-841685811. In a nutshell, a certain amount of gas is simply inaccessible because of [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md).

I have two points to make here. First, a recent change to l2geth made it so that contract OOG would be correctly surfaced **as long as you do NOT provide a gas limit** because `eth_estimateGas` will give you the message ["gas required exceeds allowance"](https://github.com/ethereum-optimism/optimism/blob/467d6cb6a4a35f2f8c3ea4cfa4babc619bafe7d2/l2geth/internal/ethapi/api.go#L1134). I believe this is *probably* good enough to catch this issue in most cases.

Second, I think we only have one reasonable fix to this problem: make the "user accessible gas limit" 1-2m gas *lower* than the actual block gas limit. E.g., if the gas limit is 9m then we only allow users to make use of 7-8m. This would "solve" the problem by hiding this discrepancy.

**Comment by smartcontracts** [comment]
Fixed in OVM 2.0 (code deleted).
