### ISSUE TITLE
Transaction block limit issue

### ISSUE THREAD

**Issue by leckylao** [ethereum-optimism/optimism#874]
https://github.com/leckylao/op-demo/issues

**Describe the bug**
This demo is to showcase two issues on Kovan OVM.
1. The current block limit on Kovan OVM is 9m. The `testPass` transaction would work with 60 times transfer for 7.1m gas. But the `testFail` transaction would fail with 70 times transfer for 7.8m gas, which still under 9m that should pass.
2. In general it would cost more gas for the same transaction in OVM than EVM and i'm wondering when/if this will become cheaper? (future versions?) and if the block limit will increase?

**To Reproduce**
## Set up

- `npm install`

- `npx hardhat compile`

- `cp .env.example .env` - put the private key in .env in order to run the test

## Unit test

`npx hardhat test test/StupidTest.js --network hardhat`

    ✓ should transfer 60 times successfully (15985ms)
    ✓ should transfer 70 times successfully (30271ms)

```
·------------------------|---------------------------|-------------|----------------------------·
|  Solc version: 0.6.12  ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 9500000 gas  │
·························|···························|·············|·····························
|  Methods                                                                                      │
··············|··········|·············|·············|·············|·············|···············
|  Contract   ·  Method  ·  Min        ·  Max        ·  Avg        ·  # calls    ·  usd (avg)   │
·-------------|----------|-------------|-------------|-------------|-------------|--------------·
```
  2 passing (1m)

## Integration test

You could look at the explorer and see the `testFail` got reverted with 7.8m gas.
https://kovan-l2-explorer.surge.sh/tx/0xbdc3f63674e704c20a03fddfe3b78dd7112a75880f6f8a1f91f573e9374c51c4

`npx hardhat test test/StupidTest.js`

testPass tx:  0xd9890d4d5a2a329ff3ff394cb2a5b54cb0d6eb3d80bf327286ff729805a03ec1
    ✓ should transfer 60 times successfully (7342ms, 8650761 gas)
testFail tx:  0xbdc3f63674e704c20a03fddfe3b78dd7112a75880f6f8a1f91f573e9374c51c4

    1) should transfer 70 times successfully
```
·---------------------------|---------------------------|-------------|----------------------------·
|   Solc version: 0.6.12    ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 6718946 gas  │
····························|···························|·············|·····························
|  Methods                                                                                         │
···············|············|·············|·············|·············|·············|···············
|  Contract    ·  Method    ·  Min        ·  Max        ·  Avg        ·  # calls    ·  usd (avg)   │
···············|············|·············|·············|·············|·············|···············
|  StupidTest  ·  testPass  ·          -  ·          -  ·    7146058  ·          1  ·           -  │
·--------------|------------|-------------|-------------|-------------|-------------|--------------·
```

  1 passing (1m)
  1 failing

  1) StupidTest
       should transfer 70 times successfully:

      AssertionError: expected '99999999400000000000' to equal '99999998700000000000'
      + expected - actual

      -99999999400000000000
      +99999998700000000000

      at Context.<anonymous> (test/StupidTest.js:75:39)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Expected behavior**
test should pass

**System Specs:**
 - OS: MacOS V10.14.6
 - Package Version (or commit hash): latest

**Additional context**
More details on https://github.com/leckylao/op-demo

**Comment by smartcontracts** [comment]
Thanks for this report :-) I've been looking for a repro case for this, so this is great.

**Comment by smartcontracts** [comment]
Confirmed. I know the underlying issue and am ruminating on a fix.

**Comment by smartcontracts** [comment]
Ok so for posterity, here's the exact issue at hand:

Although the block limit is 9m gas, the amount of gas actually available for execution is somewhat *less* than 9m (at least in the way the system is currently designed). Here's the exact reason why this is the case:
1. Transaction execution always starts with [`OVM_ExecutionManager.run`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol#L159). This is the "entrypoint" to the Optimistic Ethereum system. It's responsible for doing some setup, including calling [`_initContext`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol#L1824-L1841). `_initContext` is notable because it (necessarily) performs a series of relatively expensive SSTORE operations (setting storage variables). So there's at least ~100k L2 gas here that you have to pay for no matter what, reducing the gas limit to 9m - 100k. You can think about this as mostly equivalent to the 21k intrinsic gas of an Ethereum transaction.
2. Any transactions that are bundled by the sequencer then pass through the [`OVM_SequencerEntrypoint`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol). Although we previously used this contract to experiment with more efficient transaction encodings, we now pretty much just use it to [create contract accounts automatically on behalf of users](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol#L56-L63). Although the execution of this contract isn't particularly expensive, just the fact that we're calling another contract further reduces the amount of gas available to us because of [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md). EIP-150 introduced a new EVM rule that "all but one 64th" available gas can be passed into a `CALL` or `CREATE`. So immediately after one call, the amount of available gas is at maximum `9000000 * 63/64 = 8859375`. That's almost 150k gas that hasn't actually been *used* per se, but also isn't available for your transaction.
3. This problem is compounded by the fact that the `OVM_SequencerEntrypoint` then [calls](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol#L66-L71) [`OVM_ECDSAContractAccount.execute`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol#L57-L59). That's yet another call and yet another reduction by 1/64.
4. It doesn't stop there though! `OVM_ECDSAContractAccount` sits behind a proxy, [`OVM_ProxyEOA`](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol). Another call, another 1/64.
5. And, of course, the `OVM_ECDSAContractAccount` also has to make a [call out to the contract](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol#L103-L145) that you originally intended to call.
6. So far we have a total of four calls to get to your target contract. To make matters worse, every call in Optimistic Ethereum is (currently) actually *two* calls: contracts must call out to `OVM_ExecutionManager.ovmCALL` which will then in turn perform the relevant call out to the target contract. So we're actually performing *eight* calls before we finally hit the contract you originally wanted to call. So the maximum available gas is `9000000 * [(63/64)^8] = 7934637`. Subtract a little bit for the cost of execution inside of these contracts and you get the 7.8m gas number that you're seeing.

**Comment by leckylao** [comment]
> Ok so for posterity, here's the exact issue at hand:
> 
> Although the block limit is 9m gas, the amount of gas actually available for execution is somewhat _less_ than 9m (at least in the way the system is currently designed). Here's the exact reason why this is the case:
> 
> 1. Transaction execution always starts with [`OVM_ExecutionManager.run`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol#L159). This is the "entrypoint" to the Optimistic Ethereum system. It's responsible for doing some setup, including calling [`_initContext`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol#L1824-L1841). `_initContext` is notable because it (necessarily) performs a series of relatively expensive SSTORE operations (setting storage variables). So there's at least ~100k L2 gas here that you have to pay for no matter what, reducing the gas limit to 9m - 100k. You can think about this as mostly equivalent to the 21k intrinsic gas of an Ethereum transaction.
> 2. Any transactions that are bundled by the sequencer then pass through the [`OVM_SequencerEntrypoint`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol). Although we previously used this contract to experiment with more efficient transaction encodings, we now pretty much just use it to [create contract accounts automatically on behalf of users](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol#L56-L63). Although the execution of this contract isn't particularly expensive, just the fact that we're calling another contract further reduces the amount of gas available to us because of [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md). EIP-150 introduced a new EVM rule that "all but one 64th" available gas can be passed into a `CALL` or `CREATE`. So immediately after one call, the amount of available gas is at maximum `9000000 * 63/64 = 8859375`. That's almost 150k gas that hasn't actually been _used_ per se, but also isn't available for your transaction.
> 3. This problem is compounded by the fact that the `OVM_SequencerEntrypoint` then [calls](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol#L66-L71) [`OVM_ECDSAContractAccount.execute`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol#L57-L59). That's yet another call and yet another reduction by 1/64.
> 4. It doesn't stop there though! `OVM_ECDSAContractAccount` sits behind a proxy, [`OVM_ProxyEOA`](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol). Another call, another 1/64.
> 5. And, of course, the `OVM_ECDSAContractAccount` also has to make a [call out to the contract](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol#L103-L145) that you originally intended to call.
> 6. So far we have a total of four calls to get to your target contract. To make matters worse, every call in Optimistic Ethereum is (currently) actually _two_ calls: contracts must call out to `OVM_ExecutionManager.ovmCALL` which will then in turn perform the relevant call out to the target contract. So we're actually performing _eight_ calls before we finally hit the contract you originally wanted to call. So the maximum available gas is `9000000 * [(63/64)^8] = 7934637`. Subtract a little bit for the cost of execution inside of these contracts and you get the 7.8m gas number that you're seeing.

I see, thank you for your reply. In that case any plan/thoughts to increase block limit? As recently Ethereum also increased block limit from 9m to 15m.

**Comment by leckylao** [comment]
Oops, wrong button

**Comment by smartcontracts** [comment]
We've been aware of this issue for a while but it's pretty clear now that this is problematic. It *heavily* cuts down on the maximum available gas. However, this isn't a terribly difficult problem to solve. One approach to increase the gas limit for now is to remove `OVM_SequencerEntrypoint`, `OVM_ProxyEOA`, and `OVM_ECDSAContractAccount` in favor of moving all relevant logic into `OVM_ExecutionManager.run`. I've managed to (quite easily) [put together a pull request](https://github.com/ethereum-optimism/optimism/pull/886) that does exactly this. This solution sort of "fixes" the problem by cutting the number of calls between `run` and your target contract to just *one*. So the amount of available gas immediately shoots back up to a maximum of `9000000 * (63/64) = 8859375`. That PR also cuts down the code a bit so the gas overhead of `run` is decreased.

**Comment by smartcontracts** [comment]
We've already committed to increasing the gas limit to 10m. I'm not sure about the exact details of the discussion to increase this limit further.

**Comment by leckylao** [comment]
> We've already committed to increasing the gas limit to 10m. I'm not sure about the exact details of the discussion to increase this limit further.

Good to know. Thank you for the help.
