### ISSUE TITLE
Ensure addresses of implementation contracts are not published in documentation

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#898]
**Is your feature request related to a problem? Please describe.**

Related to #547. 

We should review our public docs, and ensure that we do not have any references to implementation contracts, especially gateway/bridge contracts.

IIRC, the Gateway and Messenger contracts were the only ones using a Proxy upgradability model.

**Comment by platocrat** [comment]
Just finished reviewing our documentation and found no mentions of either gateway.
Since we use the [contracts/deployments README](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts/deployments) to publicly list all of our contract addresses, I'm going to add a note on the README so that readers know NOT to use the regular addresses of the gateway and bridge contracts and to just use the proxied implementations.

I spoke about this with @snario as well and he agrees that this is the best solution to avoid people accidentally using our non-proxied implementations of the contracts.
