### ISSUE TITLE
Geth l2 Rojo Loco

### ISSUE THREAD

**Issue by InoMurko** [ethereum-optimism/optimism#919]
Hey!

So I've read this threat report https://blog.ethereum.org/2021/05/18/eth_state_problems/ and I wonder if Optimisms fork of Geth which is based on Rojo Loco v1.9.10 has the same issue?

And if it does or not..., is there a plan or an approach outlined how Optimism Geth fork would take changes from upstream, if at all? 

Cheers

**Comment by tynes** [comment]
There is a longer term plan to minimize the diff and use the correct abstractions such that we can attempt to automate the process of merging upstream. Ideally, Optimismtic Geth is defined by a patch file on top of geth. This problem is currently mitigated by permissioned contract deployment.

Within a few months, we will shift engineering efforts towards migrating the current optimistic geth codebase to upstream geth.

**Comment by smartcontracts** [comment]
First, to address the immediate question: we do **not** believe that these issues impact OE because these opcodes are significantly more expensive on L2 than on L1. 

@tynes already gave the right answer for the second part of your question: we do have a plan to upgrade but it's not an immediate priority at the moment.
