### ISSUE TITLE
Cannot verify contracts using hardhat-etherscan

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#979]
**Describe the bug**
@bghughes and another user in our Discord reported an issue with trying to verify their contracts on https://kovan-optimistic.etherscan.io/.

I don't know of a clear way to reproduce this issue, but a user reported the following error when attempting to verify:
```
Unable to verify on kovan optimism Etherscan has no support for network optimistic_ethereum with id 69
```

Additionally, @bghughes reported that contract verification does not appear to work for solcVersion `0.5.16`.
He also uses the `hardhat-etherscan` plugin which he noticed does not support chain `69`.

**To Reproduce**
@bghughes, maybe you could provide some more context here?

**Expected behavior**
Contract verification should be allowed with these plugins.

**Additional context**
Issues surfaced through the #support channel in our Discord.

**Comment by bghughes** [comment]
Yes - I have been trying to verify the contract found here (https://kovan-optimistic.etherscan.io/address/0x619beC3E00849e48112B162fDa1A6b1f8BC9d18F#code) and have had no success with either the Solidity (single-file) method or the Solidity (Json standard input) method.

I believe this could be due to the `0.5.16` compiler that Etherscan is using.  Also, @platocrat provided most of the key details and I am unable to use `hardhat-etherscan` to verify the contracts in my development environment.

**Comment by smartcontracts** [comment]
I believe the `hardhat-etherscan` issues are because the network is missing here: https://github.com/nomiclabs/hardhat/blob/0625c12d7f2a75056218928f4f03411e50fad0ae/packages/hardhat-etherscan/src/network/prober.ts#L35

I'll make a PR adding support for our networks. Hopefully that'll fix the issues with `hardhat-etherscan`. I'll also check in with te status of getting contracts compiled with 0.5.16 verified.

**Comment by smartcontracts** [comment]
Actually this could be a "good first issue". I'll make a new issue for it asking for someone to make a PR against `hardhat-etherscan`.

**Comment by smartcontracts** [comment]
Looks like @ayushm2003 has our backs on this one! https://github.com/nomiclabs/hardhat/pull/1493 should fix.

**Comment by platocrat** [comment]
Closing since [nomiclabs/hardhat#1493](https://github.com/nomiclabs/hardhat/pull/1493) was merged. 
Thanks again @ayushm2003! 🙏
