### ISSUE TITLE
Calling traceTransaction can cause a hang in l2geth

### ISSUE THREAD

**Issue by TerryHannant** [ethereum-optimism/optimism#990]
**Describe the bug**

When calling debug_traceTransaction sometimes no response is received. The does not appear to be related to any particular transaction or tracer used. Mulitple transactions and tracers were used with the same issue occurring.

**To Reproduce**
1. Monitor numCalls to see when it is approaching ROLLUP_DIFFDB_CACHE value
2. Call debug_traceTransaction RPC method
3. Request does not return

**Expected behavior**
traceTransaction should always return

**System Specs:**
 - OS: Debian 

**Additional context**
Possible fix

After some debugging, it appears the root cause is DiffDB. If traceTransaction is called when the max cache size (configured by ROLLUP_DIFFDB_CACHE) is reached and other transactions are being processed then a race condition can occur between DB inserts and commits. When this happens SetDiffKey hangs without returning. Further debugging shows that deadlock is occurring within the Golang SQLite lib insert and commit functions. 

Digging more into the code of api_tracer.go found a difference between traceTransaction and traceBlock/traceChain, which may be relevant.

In traceBlock a copy of statedb is used

https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/eth/api_tracer.go#L498

Whereas traceTransaction the original stateDB is used

https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/eth/api_tracer.go#L719

Looking at StateDB.Copy()

https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/core/state/statedb.go#L618

shows that the copied StateDB does not copy the DiffDB field, which turn would mean the DiffDB race condition is avoided.

So if traceTransaction is also changed to use a copy of stateDB rather than the original in

https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/eth/api_tracer.go#L719

the race condition never occurs (as there is no DiffDB) and debug_traceTransaction never hangs

**Comment by smartcontracts** [comment]
IMO we should get rid of DiffDB entirely. I'm like 95% sure we can duplicate the behavior of DiffDB via `debug_traceTransaction`... I'll take a look at this today and see if it's safe to get rid of DiffDB.

**Comment by smartcontracts** [comment]
Yeah seems like we can slightly modify `debug_traceTransaction` to get the behavior that we need. Seems better than maintaining some entirely new code for the same result.

Maybe question for @gakonst because he was the one who originally implemented DiffDB: do you think we could modify `debug_traceTransaction` instead? Code is here: https://github.com/ethereum-optimism/optimism/blob/5a7984973622d1d6e610ac98cfc206ab9a3bfe1a/l2geth/core/vm/logger.go#L140

`debug_traceTransaction` differs from what we need in two key ways. First, it only captures on *changes* to storage (SSTORE), we need to capture on SSTORE *and* SLOAD. Second, it captures by looking for SSTORE opcodes: https://github.com/ethereum-optimism/optimism/blob/5a7984973622d1d6e610ac98cfc206ab9a3bfe1a/l2geth/core/vm/logger.go#L154-L160

What we actually want here is to capture on calls to the state manager precompile: https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/core/vm/ovm_state_manager.go

**Comment by gakonst** [comment]
This makes sense to me. I think that a short-term fix would be to use a copy of the diffdb as suggested in @TerryHannant's description, and we can add this to the backlog for more stable fraud proof infrastructure. Our nodes will never expose the tracing endpoints so I think that this is not something that can be exploited.

**Comment by smartcontracts** [comment]
I think after the OVM 2.0 upgrade this problem most likely no longer exists. DiffDB has been removed and people are using traceTransaction quite frequently. Would be happy to reopen if someone finds that the hang still happens, but I doubt it will.
